version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: ibm_project_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oltp_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    