version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: ibm_project_pgsql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: softcart
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
